apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-crds
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno-crds
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 2.0.3